# Generated by Django 4.0.6 on 2023-03-03 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_img', models.DateTimeField(auto_created=True, auto_now=True)),
                ('image', models.FileField(upload_to='media')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadImg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
