# Generated by Django 4.0.6 on 2023-03-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
